### ISSUE TITLE
Filling Application logs potential fix

### ISSUE THREAD

**Issue by dougsyer** [zenoss/ZenPacks.zenoss.Microsoft.Windows#190]
Have a customer that was getting their app event log filled up (im assuming this is happening during modeling software.  Its using the old zenpack but im assuming the query still goes to WMI.

It may not be Zenoss doing this at all, not sure yet but we were able to dig up some interesting info...

Microsoft posted a suggestion on a cleaner more efficient way to grab software info here:

http://support.microsoft.com/kb/974524

here is an excerpt:

Win32_product Class is not query optimized. Queries such as “select * from Win32_Product where (name like 'Sniffer%')” require WMI to use the MSI provider to enumerate all of the installed products and then parse the full list sequentially to handle the “where” clause. This process also initiates a consistency check of packages installed, verifying and repairing the install. With an account with only user privileges, as the user account may not have access to quite a few locations, may cause delay in application launch and an event 11708 stating an installation failure. 

Win32reg_AddRemovePrograms is a much lighter and effective way to do this, which avoids the calls to do a resiliency check, especially in a locked down environment. So when using Win32reg_AddRemovePrograms we will not be calling on msiprov.dll and will not be initiating a resiliency check.

**Comment by dbouchillon** [comment]
implemented
