### ISSUE TITLE
zWinRMPassword can't be empty

### ISSUE THREAD

**Issue by cajoz** [zenoss/ZenPacks.zenoss.Microsoft.Windows#370]
If I set zWinRMUser to a valid username and keep zWinRMPassword empty, as there is no password on the target device, I get several errors during modeling complaining about a lack of a password when, in fact, the password is empty string.

While it is invalid for a username to be empty, it is completely valid for a password to be.

**Comment by dbouchillon** [comment]
event though it's valid to have no password for windows, the users of the zenpack, sysadmins, should always have a password.  we're going to keep this as is unless customers are clamoring for it to be changed.
