### ISSUE TITLE
Queries not returning data?

### ISSUE THREAD

**Issue by jregovic** [zenoss/ZenPacks.zenoss.Microsoft.Windows#623]
I am attempting to query a domain controller running Microsoft Windows Server 2012 R2 Standard and the modeler plugins for OperatingSystem, SystemEnclosure, and ComputerSystem all report no output.

From the command line, I see this:

> Get-WmiObject -Query "select * from win32_operatingsystem"
 
 
SystemDirectory : C:\WINDOWS\system32
Organization    : ORG
BuildNumber     : 9600
RegisteredUser  : ORG
SerialNumber    : xxxx
Version         : 6.3.9600

I only get the full list that the modeler is expecting if I use:

Get-WmiObject -Class Win32_OperatingSystem | select *

I'm not sure whether the query method can be updated for the modeler to attempt a different query or change from a query to a powershell command running the above.

Is this an issue that anyone else has seen?

**Comment by jregovic** [comment]
Is there some good advice on debugging an error messages? When I run the Operating system modeler, I get no results from the Win32_* wueries, but if I hack it up as a Get-WmiObject powershell command, I get results. 

Apparently, there is no connection problem, so where can I look to find any problems?

**Comment by dbouchillon** [comment]
I would say it's most likely a permissions issue.  Can you use an administrator user?

**Comment by dbouchillon** [comment]
There are also the winrm/winrs commands from the txwinrm library.  See the readme in the repo, https://github.com/zenoss/txwinrm on usage.
