### ISSUE TITLE
Feature Request: Allow for defining what DC cluster nodes go into

### ISSUE THREAD

**Issue by jstanley23** [zenoss/ZenPacks.zenoss.Microsoft.Windows#651]
Would be nice if create_device() within setClusterHostMachines() on ClusterDevice was updated to use a zProp for what device class to create the nodes in. 

This will allow for easier managing if sub classes are created with custom templates/modelers.

**Comment by dbouchillon** [comment]
Created https://jira.zenoss.com/browse/ZEN-26275 to track this issue.
