### ISSUE TITLE
MSSQL Database Monitoring Error develop branch

### ISSUE THREAD

**Issue by rebelinux** [zenoss/ZenPacks.zenoss.Microsoft.Windows#761]
SQL Server 2014

Error parsing data in powershell MSSQL strategy for "ActiveTransactions" datasource

**Comment by Ermias2000** [comment]
@rebelinux  Are you able to resolve the error parsing issue. We are getting the same error message and  if you resolved the issue would you be able to share how you did it?

Thank you!

**Comment by dsever** [comment]
Hi,
Same here what would be solution for this issue?

Dubravko
